CREATE TABLE IF NOT EXISTS CAPACITY.CAPACITY (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(90) NOT NULL
);

CREATE TABLE IF NOT EXISTS CAPACITY.BOOTCAMP_CAPACITY (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    id_capacity BIGINT NOT NULL,
    id_bootcamp BIGINT NOT NULL,
    UNIQUE KEY uq_bootcamp_capacity (id_bootcamp, id_capacity)
);

